---

  docker_compose_version: 1.23.2
  docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)"
  docker_compose_path: /usr/local/bin/docker-compose
  docker_deploy: false
